name = "browser-worker4"
main = "src/index.js"
compatibility_date = "2025-03-03"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[browser]
binding = "MYBROWSER"

[[durable_objects.bindings]]
name = "PUPPETEER_SESSIONS4"
class_name = "PuppeteerSession4"

[[migrations]]
tag = "v1"
new_classes = ["PuppeteerSession4"]
