name: Deploy All Workers

on:
  schedule:
    - cron: '0 10,18 * * *'  # Runs at 10:00 AM and 6:00 PM UTC daily
  workflow_dispatch:

concurrency:
  group: deploy-all-workers
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Deploy all workers
      run: npm run deploy-all
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

